"""300+ technical skills for resume matching (longest-first matching in parser)."""

from __future__ import annotations

# Sorted by length descending at import time in parser
SKILLS_LIBRARY: list[str] = [
    # AI / ML
    "Prompt Engineering",
    "Machine Learning",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing",
    "Large Language Models",
    "Generative AI",
    "Vector Databases",
    "LangChain",
    "LangGraph",
    "Hugging Face",
    "Transformers",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
    "OpenCV",
    "NLTK",
    "spaCy",
    "Embeddings",
    "RAG",
    "LLMs",
    "GPT-4",
    "GPT-3",
    "OpenAI",
    "Claude",
    "Gemini",
    "Anthropic",
    "Llama",
    "Mistral",
    "Stable Diffusion",
    "Midjourney",
    "Pinecone",
    "Weaviate",
    "ChromaDB",
    "FAISS",
    "MLflow",
    "Weights & Biases",
    # Languages
    "JavaScript",
    "TypeScript",
    "CoffeeScript",
    "Python",
    "Java",
    "Kotlin",
    "Scala",
    "C++",
    "C#",
    "Go",
    "Golang",
    "Rust",
    "Ruby",
    "PHP",
    "Swift",
    "Objective-C",
    "R",
    "MATLAB",
    "Dart",
    "Elixir",
    "Haskell",
    "Perl",
    "Lua",
    "Shell",
    "Bash",
    "PowerShell",
    "SQL",
    "PL/SQL",
    "T-SQL",
    "HTML5",
    "HTML",
    "CSS3",
    "CSS",
    "SASS",
    "SCSS",
    "Less",
    # Frontend
    "Next.js",
    "Nuxt.js",
    "React.js",
    "React",
    "Vue.js",
    "Vue",
    "Angular",
    "Svelte",
    "SvelteKit",
    "Remix",
    "Gatsby",
    "Ember.js",
    "jQuery",
    "Bootstrap",
    "Tailwind CSS",
    "Tailwind",
    "Material UI",
    "Chakra UI",
    "Ant Design",
    "Shadcn",
    "Webpack",
    "Vite",
    "Rollup",
    "Parcel",
    "Redux",
    "Zustand",
    "MobX",
    "RxJS",
    "Three.js",
    "D3.js",
    "Chart.js",
    "Storybook",
    "Framer Motion",
    # Backend
    "Node.js",
    "Express.js",
    "Express",
    "FastAPI",
    "Django",
    "Flask",
    "Spring Boot",
    "Spring",
    "ASP.NET",
    ".NET",
    "Ruby on Rails",
    "Rails",
    "Laravel",
    "Symfony",
    "NestJS",
    "Koa",
    "Hapi",
    "Gin",
    "Echo",
    "Fiber",
    "Actix",
    "Rocket",
    "Phoenix",
    "GraphQL",
    "REST",
    "REST API",
    "REST APIs",
    "RESTful API",
    "RESTful APIs",
    "gRPC",
    "Sass",
    "Material-UI",
    "MUI",
    "Styled Components",
    "Webpack",
    "npm",
    "GitHub Actions",
    "SOAP",
    "WebSockets",
    "Socket.io",
    "RabbitMQ",
    "Apache Kafka",
    "Kafka",
    "Celery",
    "Sidekiq",
    # Databases
    "PostgreSQL",
    "MySQL",
    "MariaDB",
    "SQLite",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "DynamoDB",
    "Cassandra",
    "CouchDB",
    "Firebase",
    "Firestore",
    "Supabase",
    "PlanetScale",
    "Neon",
    "Prisma",
    "SQLAlchemy",
    "Sequelize",
    "TypeORM",
    "Mongoose",
    # Cloud / DevOps
    "Amazon Web Services",
    "AWS",
    "Azure",
    "Google Cloud",
    "GCP",
    "Google Cloud Platform",
    "Docker",
    "Kubernetes",
    "K8s",
    "Terraform",
    "Ansible",
    "Pulumi",
    "Helm",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "CircleCI",
    "Travis CI",
    "ArgoCD",
    "Prometheus",
    "Grafana",
    "Datadog",
    "New Relic",
    "Splunk",
    "ELK Stack",
    "Nginx",
    "Apache",
    "Linux",
    "Ubuntu",
    "CentOS",
    "Windows Server",
    "CI/CD",
    "DevOps",
    "Site Reliability Engineering",
    "SRE",
    # Mobile
    "React Native",
    "Flutter",
    "Android",
    "iOS",
    "Xamarin",
    "Ionic",
    "Expo",
    # Data / Analytics
    "Apache Spark",
    "Spark",
    "Hadoop",
    "Hive",
    "Presto",
    "Airflow",
    "dbt",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "Databricks",
    "Pandas",
    "NumPy",
    "SciPy",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "Power BI",
    "Tableau",
    "Looker",
    "ETL",
    "Data Warehousing",
  # Security
    "Cybersecurity",
    "OAuth",
    "JWT",
    "SAML",
    "OWASP",
    "Penetration Testing",
    "Encryption",
    # Tools
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Jira",
    "Confluence",
    "Notion",
    "Figma",
    "Adobe XD",
    "Sketch",
    "Postman",
    "Insomnia",
    "Swagger",
    "OpenAPI",
    "WordPress",
    "Elementor",
    "Shopify",
    "Salesforce",
    "HubSpot",
    "SAP",
    "Oracle",
    # Methodologies
    "Agile",
    "Scrum",
    "Kanban",
    "SAFe",
    "TDD",
    "BDD",
    "Microservices",
    "Serverless",
    "Event-Driven Architecture",
    "System Design",
    "API Integration",
    "Automation",
    # CS fundamentals (often listed on resumes)
    "Data Structures",
    "Algorithms",
    "OOP",
    "Object-Oriented Programming",
    "DBMS",
    "Operating Systems",
    "Computer Networks",
    "Distributed Systems",
    "Design Patterns",
    # More web / misc
    "WebRTC",
    "PWA",
    "SSR",
    "SSG",
    "SEO",
    "Accessibility",
    "WCAG",
    "Stripe",
    "PayPal",
    "Twilio",
    "SendGrid",
    "Auth0",
    "Keycloak",
    "Apache",
    "Tomcat",
    "WildFly",
    "Istio",
    "Linkerd",
    "Consul",
    "Vault",
    "Nomad",
    "Vagrant",
    "Packer",
    "CloudFormation",
    "CloudWatch",
    "Lambda",
    "EC2",
    "S3",
    "RDS",
    "ECS",
    "EKS",
    "GCP Cloud Run",
    "Cloud Functions",
    "App Engine",
    "Heroku",
    "Vercel",
    "Netlify",
    "Railway",
    "Render",
    "Fly.io",
    "DigitalOcean",
    "Linode",
    "C",
    "C++",
    "CUDA",
    "OpenGL",
    "Unity",
    "Unreal Engine",
    "Blender",
    "Solidity",
    "Blockchain",
    "Web3",
    "Ethereum",
    "Hardhat",
    "Truffle",
    "IPFS",
    "Streamlit",
    "Gradio",
    "FastAPI",
    "Pydantic",
    "Uvicorn",
    "Gunicorn",
    "NPM",
    "Yarn",
    "pnpm",
    "Bun",
    "Deno",
    "esbuild",
    "SWC",
    "Babel",
    "ESLint",
    "Prettier",
    "Jest",
    "Mocha",
    "Chai",
    "Cypress",
    "Playwright",
    "Selenium",
    "PyTest",
    "unittest",
    "JUnit",
    "TestNG",
    "Mockito",
    "SonarQube",
    "Codecov",
    "Sentry",
    "LogRocket",
    "Mixpanel",
    "Amplitude",
    "Segment",
    "Apache Beam",
    "Flink",
    "Storm",
    "Zookeeper",
    "etcd",
    "Memcached",
    "Varnish",
    "CDN",
    "Cloudflare",
    "Akamai",
    "MVC",
    "MVVM",
    "CQRS",
    "Domain-Driven Design",
    "DDD",
    "Hexagonal Architecture",
    "Clean Architecture",
    "SOLID",
    "Functional Programming",
    "Reactive Programming",
    "Protocol Buffers",
    "Avro",
    "Parquet",
    "ORC",
    "JSON",
    "XML",
    "YAML",
    "TOML",
    "Markdown",
    "LaTeX",
    "Selenium Grid",
    "Appium",
    "Detox",
    "XCTest",
    "Espresso",
    "Robot Framework",
    "Behave",
    "Cucumber",
    "SpecFlow",
    "Gherkin",
    "WireMock",
    "Mountebank",
    "Locust",
    "JMeter",
    "Gatling",
    "k6",
    "Artillery",
    "PagerDuty",
    "Opsgenie",
    "VictorOps",
    "Slack API",
    "Discord API",
    "Telegram Bot API",
    "WhatsApp API",
    "Zapier",
    "Make",
    "n8n",
    "Airbyte",
    "Fivetran",
    "Stitch",
    "Talend",
    "Informatica",
    "SSIS",
    "Crystal Reports",
    "SSRS",
    "Apache Superset",
    "Metabase",
    "Apache Druid",
    "ClickHouse",
    "TimescaleDB",
    "InfluxDB",
    "Prometheus",
    "Thanos",
    "Loki",
    "Jaeger",
    "Zipkin",
    "OpenTelemetry",
    "OpenTracing",
    "Istio",
    "Envoy",
    "HAProxy",
    "Traefik",
    "Kong",
    "Apigee",
    "MuleSoft",
    "WSO2",
    "Tibco",
    "BizTalk",
    "IBM MQ",
    "ActiveMQ",
    "ZeroMQ",
    "NATS",
    "Pulsar",
    "Solace",
    "Debezium",
    "Canal",
    "Maxwell",
    "Sqoop",
    "Flume",
    "NiFi",
    "Kettle",
    "Pentaho",
]

# Deduplicate preserving first canonical form
_seen: set[str] = set()
_UNIQUE: list[str] = []
for skill in SKILLS_LIBRARY:
    key = skill.lower()
    if key not in _seen:
        _seen.add(key)
        _UNIQUE.append(skill)

SKILLS_LIBRARY = _UNIQUE
assert len(SKILLS_LIBRARY) >= 300, f"Expected 300+ skills, got {len(SKILLS_LIBRARY)}"
