/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResumeRouteImport } from './routes/app.resume'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOpportunitiesRouteImport } from './routes/app.opportunities'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppAutomationRouteImport } from './routes/app.automation'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as SiteWaitlistRouteImport } from './routes/_site.waitlist'
import { Route as SitePricingRouteImport } from './routes/_site.pricing'
import { Route as SiteIntegrationsRouteImport } from './routes/_site.integrations'
import { Route as SiteHelpRouteImport } from './routes/_site.help'
import { Route as SiteFeaturesRouteImport } from './routes/_site.features'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const SiteWaitlistRoute = SiteWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIntegrationsRoute = SiteIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SiteRoute,
} as any)
const SiteHelpRoute = SiteHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFeaturesRoute = SiteFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/features': typeof SiteFeaturesRoute
  '/help': typeof SiteHelpRoute
  '/integrations': typeof SiteIntegrationsRoute
  '/pricing': typeof SitePricingRoute
  '/waitlist': typeof SiteWaitlistRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/automation': typeof AppAutomationRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/features': typeof SiteFeaturesRoute
  '/help': typeof SiteHelpRoute
  '/integrations': typeof SiteIntegrationsRoute
  '/pricing': typeof SitePricingRoute
  '/waitlist': typeof SiteWaitlistRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/automation': typeof AppAutomationRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_site/features': typeof SiteFeaturesRoute
  '/_site/help': typeof SiteHelpRoute
  '/_site/integrations': typeof SiteIntegrationsRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/waitlist': typeof SiteWaitlistRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/automation': typeof AppAutomationRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/features'
    | '/help'
    | '/integrations'
    | '/pricing'
    | '/waitlist'
    | '/app/analytics'
    | '/app/applications'
    | '/app/automation'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/profile'
    | '/app/resume'
    | '/app/settings'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/features'
    | '/help'
    | '/integrations'
    | '/pricing'
    | '/waitlist'
    | '/app/analytics'
    | '/app/applications'
    | '/app/automation'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/profile'
    | '/app/resume'
    | '/app/settings'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_site'
    | '/app'
    | '/login'
    | '/signup'
    | '/_site/features'
    | '/_site/help'
    | '/_site/integrations'
    | '/_site/pricing'
    | '/_site/waitlist'
    | '/app/analytics'
    | '/app/applications'
    | '/app/automation'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/profile'
    | '/app/resume'
    | '/app/settings'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resume': {
      id: '/app/resume'
      path: '/resume'
      fullPath: '/app/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities': {
      id: '/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automation': {
      id: '/app/automation'
      path: '/automation'
      fullPath: '/app/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/waitlist': {
      id: '/_site/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof SiteWaitlistRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/integrations': {
      id: '/_site/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof SiteIntegrationsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/help': {
      id: '/_site/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof SiteHelpRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/features': {
      id: '/_site/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof SiteFeaturesRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteFeaturesRoute: typeof SiteFeaturesRoute
  SiteHelpRoute: typeof SiteHelpRoute
  SiteIntegrationsRoute: typeof SiteIntegrationsRoute
  SitePricingRoute: typeof SitePricingRoute
  SiteWaitlistRoute: typeof SiteWaitlistRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteFeaturesRoute: SiteFeaturesRoute,
  SiteHelpRoute: SiteHelpRoute,
  SiteIntegrationsRoute: SiteIntegrationsRoute,
  SitePricingRoute: SitePricingRoute,
  SiteWaitlistRoute: SiteWaitlistRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppAutomationRoute: typeof AppAutomationRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResumeRoute: typeof AppResumeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppAutomationRoute: AppAutomationRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppProfileRoute: AppProfileRoute,
  AppResumeRoute: AppResumeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
